Add support of Qt6 and fixes an include of <optional>.
letsfindaway/OpenBoard pull request #166
Opened 2024-02-14 21:57 UTC by sebojolais

2024-02-15 06:56 UTC, letsfindaway commented
Thanks for your contribution! I will review it when I'm back next Tuesday.

2024-02-20 07:34 UTC, letsfindaway requested changes

2024-02-20 07:34 UTC, letsfindaway commented on src/gui/UBBackgroundManager.cpp
> +        const auto ruling = background(QUuid(QAnyStringView(uuid)));
Is it really necessary to explicitly construct a `QAnyStringView` first before creating the `QUuid`? As `QAnyStringView` is introduced with Qt 6.4, this would inhibit compilation with Qt 6.2.

2024-02-20 20:41 UTC, sebojolais commented on src/gui/UBBackgroundManager.cpp
> +        const auto ruling = background(QUuid(QAnyStringView(uuid)));
QAnyStringView was introduced in Qt 6.0 https://doc.qt.io/qt-6/qanystringview.html.
Anyway a simple call:
`        const auto ruling = background(QUuid::fromString(uuid));
`
is better with no mention to QAnyStringView and no Qt version checking by the pre-processor.

2024-02-21 06:32 UTC, letsfindaway commented on src/gui/UBBackgroundManager.cpp
> +        const auto ruling = background(QUuid(QAnyStringView(uuid)));
Perfect!

2024-02-21 06:33 UTC, letsfindaway approved these changes

2024-02-21 06:34 UTC, merged